# Docker compose file for dnsmasq
version: '3'

services:
  app:
    image: dnsmasq:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - HTTP_USER=${HTTP_USER}
        - HTTP_PASS=${HTTP_PASS}
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASS=${HTTP_PASS}
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - dnsmasq-network
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:8080"
    restart: unless-stopped

networks:
  dnsmasq-network:
      driver: bridge
